SET local check_function_bodies = off;

DROP POLICY "authenticated_select_activity" ON "public"."daily_scholar_activity";

DROP POLICY "mcf_select_own_or_leaders" ON "public"."mcf_form_logs";

DROP POLICY "whaf_select_own_or_leaders" ON "public"."whaf_form_logs";

DROP POLICY "wpl_select_own_or_leaders" ON "public"."wpl_form_logs";

DROP FUNCTION "public"."roster_uid"();

CREATE EXTENSION "btree_gist" SCHEMA "public";

CREATE EXTENSION "hypopg" SCHEMA "extensions";

CREATE EXTENSION "index_advisor" SCHEMA "extensions";

CREATE EXTENSION "pg_cron";

CREATE EXTENSION "pgjwt" SCHEMA "extensions";

CREATE TABLE "public"."calendar_events" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "google_event_id" text                     NOT NULL,
  "title"           text                     NOT NULL,
  "description"     text,
  "location"        text,
  "start_time"      timestamp with time zone NOT NULL,
  "end_time"        timestamp with time zone NOT NULL,
  "status"          text                     NOT NULL DEFAULT 'confirmed'::text,
  "recording_url"   text,
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "calendar_events_google_event_id_key" UNIQUE (google_event_id),
  CONSTRAINT "calendar_events_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."calendar_events"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."calendar_sync_state" (
  "id"             integer                  NOT NULL DEFAULT 1,
  "sync_token"     text,
  "last_synced_at" timestamp with time zone,
  CONSTRAINT "calendar_sync_state_pkey" PRIMARY KEY (id),
  CONSTRAINT "singleton" CHECK ((id = 1))
);

ALTER TABLE "public"."calendar_sync_state"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."career_opportunities" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "link"       text,
  CONSTRAINT "career_opportunities_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."career_opportunities"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."notification_log" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "event_type"      text                     NOT NULL,
  "event_ref_id"    text,
  "recipient_id"    uuid                     NOT NULL,
  "channel"         text                     NOT NULL,
  "channel_target"  text                     NOT NULL,
  "payload"         jsonb                    NOT NULL,
  "status"          text                     NOT NULL DEFAULT 'pending'::text,
  "error"           text,
  "attempt_count"   integer                  NOT NULL DEFAULT 0,
  "idempotency_key" text                     NOT NULL,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "sent_at"         timestamp with time zone,
  CONSTRAINT "notification_log_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "notification_log_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."notification_log"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."scholar_shift_assignments" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "scholar_id"  text                     NOT NULL,
  "semester_id" integer                  NOT NULL,
  "day_of_week" smallint                 NOT NULL,
  "start_time"  time without time zone   NOT NULL,
  "end_time"    time without time zone   NOT NULL,
  "is_active"   boolean                  NOT NULL DEFAULT true,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "scholar_shift_assignments_check" CHECK ((end_time > start_time)),
  CONSTRAINT "scholar_shift_assignments_day_of_week_check" CHECK (((day_of_week >= 0) AND (day_of_week <= 6))),
  CONSTRAINT "scholar_shift_assignments_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."scholar_shift_assignments"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."scholar_shift_assignments"
  ADD COLUMN "week_minute_range" int4range GENERATED ALWAYS AS
    (int4range(((day_of_week * 1440) + (((EXTRACT(hour FROM start_time))::integer * 60) + (EXTRACT(minute FROM start_time))::integer)), ((day_of_week * 1440) + (((EXTRACT(hour FROM
    end_time))::integer * 60) + (EXTRACT(minute FROM end_time))::integer)))) STORED;

CREATE TYPE "public"."session_kind" AS ENUM (
  'front_desk',
  'study_session'
);

ALTER TABLE "public"."scholar_shift_assignments"
  ADD COLUMN "session_kind" public.session_kind NOT NULL;

CREATE OR REPLACE FUNCTION public.is_team_leader_or_above()
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.app_role = ANY (
        ARRAY[
          'admin'::text,
          'staff'::text,
          'teamleader'::text,
          'team_leader'::text,
          'developer'::text,
          'exec'::text
        ]
      )
  );
$function$;

CREATE OR REPLACE FUNCTION public.mentor_mentee_sync_trigger()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM public.sync_mentee_denormalization(OLD.mentor_id);
    RETURN OLD;
  ELSE
    PERFORM public.sync_mentee_denormalization(NEW.mentor_id);
    RETURN NEW;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.replace_mentor_mentee_assignments (
  p_mentor_id   uuid,
  p_mentee_uids text[]
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
BEGIN
  IF NOT public.is_developer() THEN
    RAISE EXCEPTION 'Forbidden: developer access required' USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.mentor_mentee WHERE mentor_id = p_mentor_id;

  IF p_mentee_uids IS NOT NULL AND array_length(p_mentee_uids, 1) > 0 THEN
    INSERT INTO public.mentor_mentee (mentor_id, mentee_uid)
    SELECT p_mentor_id, uid FROM unnest(p_mentee_uids) AS uid;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_mentee_denormalization (
  p_mentor_id uuid
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
DECLARE
  v_student_id text;
  v_mentee_uids text[];
  v_count integer;
BEGIN
  SELECT student_id INTO v_student_id FROM public.profiles WHERE id = p_mentor_id;

  SELECT COALESCE(array_agg(mentee_uid ORDER BY mentee_uid), '{}'::text[]),
         COALESCE(count(*), 0)
    INTO v_mentee_uids, v_count
    FROM public.mentor_mentee
    WHERE mentor_id = p_mentor_id;

  UPDATE public.profiles SET mentee_count = v_count WHERE id = p_mentor_id;

  IF v_student_id IS NOT NULL THEN
    UPDATE public.user_roster
       SET mentee_count = v_count, mentee_uids = v_mentee_uids
     WHERE uid = v_student_id;
  END IF;
END;
$function$;

ALTER TABLE "public"."notification_log"
  ADD CONSTRAINT "notification_log_recipient_id_fkey" FOREIGN KEY (recipient_id) REFERENCES public.profiles(id);

ALTER TABLE "public"."scholar_shift_assignments"
  ADD CONSTRAINT "no_overlapping_shift_assignments" EXCLUDE USING gist (scholar_id WITH =, week_minute_range WITH &&) WHERE (is_active);

ALTER TABLE "public"."scholar_shift_assignments"
  ADD CONSTRAINT "scholar_shift_assignments_scholar_id_fkey" FOREIGN KEY (scholar_id) REFERENCES public.user_roster(uid) ON DELETE CASCADE;

ALTER TABLE "public"."scholar_shift_assignments"
  ADD CONSTRAINT "scholar_shift_assignments_semester_id_fkey" FOREIGN KEY (semester_id) REFERENCES public.semesters(id) ON DELETE CASCADE;

CREATE INDEX daily_scholar_activity_duration_minutes_idx ON public.daily_scholar_activity USING btree (duration_minutes);

CREATE INDEX idx_calendar_events_start_time ON public.calendar_events USING btree (start_time);

CREATE INDEX idx_shift_assignments_scholar ON public.scholar_shift_assignments USING btree (scholar_id)
  WHERE is_active;

CREATE INDEX idx_shift_assignments_semester_kind ON public.scholar_shift_assignments USING btree (semester_id, session_kind, day_of_week)
  WHERE is_active;

CREATE INDEX notification_log_event_type_status_idx ON public.notification_log USING btree (event_type, status);

CREATE INDEX notification_log_recipient_id_created_at_idx ON public.notification_log USING btree (recipient_id, created_at DESC);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER mentor_mentee_sync
  AFTER INSERT OR DELETE OR UPDATE ON public.mentor_mentee
  FOR EACH ROW
  EXECUTE FUNCTION public.mentor_mentee_sync_trigger();

CREATE POLICY "authenticated_select_activity" ON "public"."daily_scholar_activity"
  FOR SELECT
  TO "authenticated"
  USING (((scholar_uid = (( SELECT auth.uid() AS uid))::text) OR (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.app_role = ANY (ARRAY['admin'::text, 'staff'::text, 'team_leader'::text, 'developer'::text])))))));

CREATE POLICY "team_leader_read_mentor_mentee" ON "public"."mentor_mentee"
  FOR SELECT
  TO "authenticated"
  USING (public.is_team_leader_or_above());

CREATE POLICY "team_leader_read_profiles" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING (public.is_team_leader_or_above());

CREATE POLICY "scholar_shift_assignments_select_authenticated" ON "public"."scholar_shift_assignments"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "scholar_shift_assignments_write_admin" ON "public"."scholar_shift_assignments"
  FOR ALL
  TO "authenticated"
  USING ((( SELECT profiles.app_role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = 'admin'::text))
  WITH CHECK ((( SELECT profiles.app_role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = 'admin'::text));

CREATE POLICY "whaf_select_policy" ON "public"."whaf_form_logs"
  FOR ALL
  TO "authenticated"
  USING (((scholar_uid = (( SELECT auth.uid() AS uid))::text) OR (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.app_role = ANY (ARRAY['admin'::text, 'staff'::text, 'team_leader'::text, 'developer'::text])))))));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

COMMENT ON COLUMN "public"."scholar_shift_assignments"."day_of_week" IS 'sunday = 0, monday = 1, etc.';

COMMENT ON COLUMN "public"."scholar_shift_assignments"."scholar_id" IS 'References user_roster.uid (text), NOT profiles.id. user_roster is scholars'' staging table until they get real app accounts in profiles -- this will need re-pointing at profiles(id) in a future migration once that happens. This is also the same value stored in front_desk_logs.scholar_uid / study_session_logs.scholar_uid, so no bridge table is needed to join assignments to logs.';

COMMENT ON COLUMN "public"."scholar_shift_assignments"."week_minute_range" IS 'Generated column, exists solely to support no_overlapping_shift_assignments. Not meaningful outside that constraint.';

COMMENT ON EXTENSION "btree_gist" IS 'support for indexing common datatypes in GiST';

COMMENT ON EXTENSION "hypopg" IS 'Hypothetical indexes for PostgreSQL';

COMMENT ON EXTENSION "index_advisor" IS 'Query index advisor';

COMMENT ON EXTENSION "pg_cron" IS 'Job scheduler for PostgreSQL';

COMMENT ON EXTENSION "pgjwt" IS 'JSON Web Token API for Postgresql';

COMMENT ON TABLE "public"."scholar_shift_assignments" IS 'Standing semester-long front-desk / study-session shift assignment for a scholar. One row per scholar per assignment; not re-created weekly. Compliance against front_desk_logs/study_session_logs is computed on read, not stored here or elsewhere.';

GRANT EXECUTE ON FUNCTION "public"."mentor_mentee_sync_trigger"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."replace_mentor_mentee_assignments"(uuid, text[]) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."sync_mentee_denormalization"(uuid) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."calendar_events" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."calendar_sync_state" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."career_opportunities" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notification_log" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."scholar_shift_assignments" TO "anon", "authenticated", "postgres", "service_role";

GRANT USAGE ON TYPE "public"."session_kind" TO "postgres";

SELECT cron.schedule_in_database('nightly_resync_daily_scholar_activity', '0 2 * * *', 'SELECT public.full_resync_daily_scholar_activity();', 'postgres', NULL, true);

